# Otras medidas de riesgo y rendimiento

In [76]:
import pandas as pd; import numpy as np; import yfinance as yf

In [77]:
tickers = ['WMT', 'COST']

In [78]:
prices = yf.download(tickers, start='2020-01-01', end='2026-09-07')['Close']
prices

[*********************100%***********************]  2 of 2 completed

Ticker            COST         WMT
Date
2020-01-02  265.326416   36.203289
2020-01-03  265.544952   35.883686
2020-01-06  265.617798   35.810627
2020-01-07  265.199066   35.478859
2020-01-08  268.239380   35.357105
...                ...         ...
2026-08-31  943.890015  104.870003
2026-09-01  939.960022  105.919998
2026-09-02  928.479980  106.089996
2026-09-03  925.409973  108.419998
2026-09-04  915.739990  107.139999

[1678 rows x 2 columns]

In [79]:
rets = prices.pct_change().dropna()
rets

Ticker          COST       WMT
Date
2020-01-03  0.000824 -0.008828
2020-01-06  0.000274 -0.002036
2020-01-07 -0.001576 -0.009265
2020-01-08  0.011464 -0.003432
2020-01-09  0.016050  0.010331
...              ...       ...
2026-08-31 -0.001671  0.017267
2026-09-01 -0.004164  0.010012
2026-09-02 -0.012213  0.001605
2026-09-03 -0.003306  0.021963
2026-09-04 -0.010449 -0.011806

[1677 rows x 2 columns]

### Rendimiento esperado $E[R_i]$ (FL)

In [80]:
rets.mean() * 252 * 100

Ticker
COST    21.380278
WMT     19.078702
dtype: float64

**Si invierto en un activo a largo plazo, espero ganar en promedio $x$.**

### Media geométrica - $CAGR$ (Compound Annual Growth Rate) $R_G$ (BL)

Representa el rendimiento compuesto:

$$
R_G
=
\left(
\prod_{i=1}^{n}(1+r_i)
\right)^{\frac{1}{n}}
-1
$$

In [81]:
CAGR = ((rets + 1).prod() ** (1 / len(rets))) - 1
CAGR * 252 * 100

Ticker
COST    18.621692
WMT     16.309186
dtype: float64

**Si invierto mi capital y cada periodo reinvierto lo ganado, a largo plazo espero generar $x$.**

Nota: **$CAGR < E[R_i]$**, siempre y para todos los casos. Conforme la varianza aumenta, esta diferencia se nota aun más. 

El CAGR se considera si quieres considerar reinversiones en el capital y quieres ver tu <u>rendimiento real</u>, el promedio es solo para mirar a futuro y ver una proyección.

### Media armónica (BL)

Esta medida es muy útil cuando se trabaja con datos con volatilidad alta y con outliers, ya que mitiga su influencia en el resultado final:

$$
R_H
=
\frac{n}
{\displaystyle \sum_{i=1}^{n}\frac{1}{1+r_i}}
-1
$$

In [82]:
MA = (len(rets) / ((1 / (rets + 1)).sum())) - 1
MA * 252 * 100

Ticker
COST    15.853395
WMT     13.531273
dtype: float64

Este rendimiento armónico, al mitigar los outliers, siempre va a ser menor que el $CAGR$ y que la media.

Entre más varianza, más diferencia porcentual habrá en las medias.

## Medidas probabilísticas

### Rendimiento Esperado (FL)

Este rendimiento es probabilístico en el corto plazo.

In [83]:
df = pd.DataFrame()
df['Escenario'] = ['Bajista', 'Neutral', 'Alcista']
df['Probabilidad'] = [0.25, 0.3, 0.45]
df['Rendimiento'] = [-10, 5, 20]

df

  Escenario  Probabilidad  Rendimiento
0   Bajista          0.25          -10
1   Neutral          0.30            5
2   Alcista          0.45           20

In [84]:
E_R = (df['Probabilidad'] * df['Rendimiento']).sum()
E_R

np.float64(8.0)

**En base a las probabilidades de cada escenario económico, en el corto plazo espero ganar $x$.**

*Capital Market Expectations*

Es lo que se usa para calcular probabilidades.

### Varianza Esperada (FL)

In [85]:
E_V = (df['Probabilidad'] * ((df['Rendimiento'] - E_R) ** 2)).sum()
E_V

np.float64(148.5)

### Volatilidad Esperada (FL)

In [86]:
E_vol = np.sqrt(E_V)
E_vol

np.float64(12.186057606953941)

# Ejercicio

In [87]:
ej = pd.DataFrame()
ej['Escenario'] = ['Dovish', 'Neutral', 'Hawkish']
ej['Probabilidad'] = [0.7, 0.2, 0.1]
ej['Rendimiento'] = [2, 3, 5.5]

ej

  Escenario  Probabilidad  Rendimiento
0    Dovish           0.7          2.0
1   Neutral           0.2          3.0
2   Hawkish           0.1          5.5

In [88]:
E_R_ej = (ej['Probabilidad'] * ej['Rendimiento']).sum()
E_R_ej

np.float64(2.55)

In [89]:
E_V_ej = (ej['Probabilidad'] * ((ej['Rendimiento'] - E_R_ej) ** 2)).sum()
E_V_ej

np.float64(1.1225)

In [90]:
E_vol_ej = np.sqrt(E_V_ej)
E_vol_ej

np.float64(1.0594810050208545)