# Rendimiento y riesgo de un portafolio

Librerías

In [1]:
import pandas as pd
import numpy as np
import yfinance as yf

Definimos tickers de las acciones a trabajar

In [2]:
tickers = ['NVDA', 'WMT']

Descargamos los precios de cierre

In [3]:
prices = yf.download(tickers, start='2024-01-01', end='2026-08-26')['Close']
prices

[*********************100%***********************]  2 of 2 completed

Ticker            NVDA         WMT
Date
2024-01-02   48.082535   51.641453
2024-01-03   47.484596   51.644703
2024-01-04   47.912842   51.145439
2024-01-05   49.009884   50.805031
2024-01-08   52.160282   51.304295
...                ...         ...
2026-08-19  217.559998  114.027023
2026-08-20  216.850006  103.591995
2026-08-21  214.720001  103.699997
2026-08-24  208.479996  106.489998
2026-08-25  213.050003  105.379997

[664 rows x 2 columns]

## Rendimeinto del portafolio

$$
E(R_p)=\sum_{i=1}^{n} w_i E(R_i)
$$

Calcular rendimientos diarios individuales

In [4]:
rets = (prices / prices.shift() - 1).dropna()
rets

Ticker          NVDA       WMT
Date
2024-01-03 -0.012436  0.000063
2024-01-04  0.009019 -0.009667
2024-01-05  0.022897 -0.006656
2024-01-08  0.064281  0.009827
2024-01-09  0.016975  0.006698
...              ...       ...
2026-08-19 -0.009921 -0.007812
2026-08-20 -0.003263 -0.091514
2026-08-21 -0.009822  0.001043
2026-08-24 -0.029061  0.026905
2026-08-25  0.021921 -0.010424

[663 rows x 2 columns]

Rendimientos promedio / rendimiento esperado (anual)

In [5]:
mu = rets.mean() * 252
mu * 100

Ticker
NVDA    68.200415
WMT     29.867540
dtype: float64

Rendimiento del portafolio

In [6]:
w_port = np.array([0.5, 0.5]) # Pesos de los activos
w_port

array([0.5, 0.5])

In [ ]:
r_port = sum(w_port * mu) # Matemáticamente se realiza un producto punto 
r_port

0.49033977382890154

$$
\vec{R_p} = (r_x, r_y)
$$

$$
\vec{W} = (w_x, w_y)
$$

$$
\vec{R_p}\cdot\vec{W}
=
r_x \cdot w_x + r_y \cdot w_y
$$

Con 2 activos es fácil, pero con más, se puede volver complicado, así que podemos usar lo siguiente:

$$
E(R_p) = w^T R
$$

## Riesgo del portafolio
$$
\sigma_p^2
=
\sum_{i=1}^{n}
\sum_{j=1}^{n}
X_i X_j \sigma_{i,j}
$$

Aquí no podemos considerar el riesgo de un activo por sí solo, debemos calcular también si hay relación entre los activos. Es decir, hay que considerar el efecto de interacción entre los activos.

In [23]:
rets.var()

Ticker
NVDA    0.000922
WMT     0.000218
dtype: float64

In [19]:
annual_var = rets.var() * 252
annual_var

Ticker
NVDA    0.232222
WMT     0.054965
dtype: float64

In [20]:
# Covarianzas
cov = rets.cov()
cov

Ticker      NVDA       WMT
Ticker
NVDA    0.000922  0.000014
WMT     0.000014  0.000218

Varianza

In [21]:
var_port = w_port[0] ** 2 * rets.var()[0] + 2 * w_port[0] * w_port[1] * cov.iloc[0, 1] + w_port[1] ** 2 * rets.var()[1]
var_port

C:\Users\gibra\AppData\Local\Temp\ipykernel_94752\803577782.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  var_port = w_port[0] ** 2 * rets.var()[0] + 2 * w_port[0] * w_port[1] * cov.iloc[0, 1] + w_port[1] ** 2 * rets.var()[1]

np.float64(0.00029210332812123796)

Desviación estándar

In [22]:
desv_port = np.sqrt(var_port)
desv_port

np.float64(0.017091030633675605)

De igual modo, esto es fácil si hay 2 activos, pero con más activos, se vuelve complicado, por lo que se resume a esta formula:

$$
\sigma_p^2 = w^T \Sigma w
$$

In [24]:
cov

Ticker      NVDA       WMT
Ticker
NVDA    0.000922  0.000014
WMT     0.000014  0.000218

In [25]:
w_port

array([0.5, 0.5])

**`*`**: Multiplicación escalar

**`@`**: Multiplicación matricial

Varianza (Riesgo)

In [ ]:
w_port.T@cov@w_port

np.float64(0.0002921033281212379)

Desviación estándar (Volatilidad)

In [27]:
np.sqrt(w_port.T@cov@w_port)

np.float64(0.017091030633675605)